version: '3'
services:
  php72:
    build:
      context: .
      dockerfile: Dockerfile.php72
    volumes:
      - .:/app
      - /app/vendor/
    command: >
      sh -c "
        composer install --no-interaction > /dev/null 2>&1 &&
        phpunit -c phpunit8.xml
      "
  php74:
    build:
      context: .
      dockerfile: Dockerfile.php74
    volumes:
      - .:/app
      - /app/vendor/
    command: >
      sh -c "
        composer install --no-interaction > /dev/null 2>&1 &&
        phpunit -c phpunit9.xml
      "
  php80:
    build:
      context: .
      dockerfile: Dockerfile.php80
    volumes:
      - .:/app
      - /app/vendor/
    command: >
      sh -c "
        composer install --no-interaction > /dev/null 2>&1 &&
        phpunit -c phpunit9.xml
      "
  php81:
    build:
      context: .
      dockerfile: Dockerfile.php81
    volumes:
      - .:/app
      - /app/vendor/
    command: >
      sh -c "
        composer install --no-interaction > /dev/null 2>&1 &&
        phpunit -c phpunit10.xml
      "
  php82:
    build:
      context: .
      dockerfile: Dockerfile.php82
    volumes:
      - .:/app
      - /app/vendor/
    command: >
      sh -c "
        composer install --no-interaction > /dev/null 2>&1 &&
        phpunit -c phpunit10.xml
      "