version: '3'
services:
  test-php7.2:
    build:
      context: .
      dockerfile: .docker/Dockerfile.php72
    volumes:
      - .:/app
      - /app/vendor/
    command: >
      sh -c "
        composer install --no-interaction > /dev/null 2>&1 &&
        phpunit -c phpunit8.xml
      "
  test-php7.4:
    build:
      context: .
      dockerfile: .docker/Dockerfile.php74
    volumes:
      - .:/app
      - /app/vendor/
    command: >
      sh -c "
        composer install --no-interaction > /dev/null 2>&1 &&
        phpunit -c phpunit9.xml
      "
  test-php8.0:
    build:
      context: .
      dockerfile: .docker/Dockerfile.php80
    volumes:
      - .:/app
      - /app/vendor/
    command: >
      sh -c "
        composer install --no-interaction > /dev/null 2>&1 &&
        phpunit -c phpunit9.xml
      "
  test-php8.1:
    build:
      context: .
      dockerfile: .docker/Dockerfile.php81
    volumes:
      - .:/app
      - /app/vendor/
    command: >
      sh -c "
        composer install --no-interaction > /dev/null 2>&1 &&
        phpunit -c phpunit10.xml
      "
  test-php8.2:
    build:
      context: .
      dockerfile: .docker/Dockerfile.php82
    volumes:
      - .:/app
      - /app/vendor/
    command: >
      sh -c "
        composer install --no-interaction > /dev/null 2>&1 &&
        phpunit -c phpunit10.xml
      "